// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MovieBuff.Data;

namespace MovieBuff.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20210921133648_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.10")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("CastMemberMedia", b =>
                {
                    b.Property<int>("CastId")
                        .HasColumnType("int");

                    b.Property<int>("StarredMediaId")
                        .HasColumnType("int");

                    b.HasKey("CastId", "StarredMediaId");

                    b.HasIndex("StarredMediaId");

                    b.ToTable("CastMemberMedia");
                });

            modelBuilder.Entity("MovieBuff.Models.CastMember", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("CastMembers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Carrie Fisher"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Mark Hamil"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Harrison Ford"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Cole Sprouse"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Lili Reinhart"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Camila Mendes"
                        },
                        new
                        {
                            Id = 7,
                            Name = "KJ Apa"
                        },
                        new
                        {
                            Id = 8,
                            Name = "James Spader"
                        },
                        new
                        {
                            Id = 9,
                            Name = "Megan Boone"
                        },
                        new
                        {
                            Id = 10,
                            Name = "Diego Klattenhoff"
                        },
                        new
                        {
                            Id = 11,
                            Name = "Henry Lennix"
                        },
                        new
                        {
                            Id = 12,
                            Name = "Daisy Ridley"
                        },
                        new
                        {
                            Id = 13,
                            Name = "Adam Driver"
                        },
                        new
                        {
                            Id = 14,
                            Name = "Natalie Portman"
                        },
                        new
                        {
                            Id = 15,
                            Name = "Ewan McGregor"
                        },
                        new
                        {
                            Id = 16,
                            Name = "Liam Neeson"
                        },
                        new
                        {
                            Id = 17,
                            Name = "Hayden Christensen"
                        },
                        new
                        {
                            Id = 18,
                            Name = "Jared Harris"
                        },
                        new
                        {
                            Id = 19,
                            Name = "Stellan Skarsgård"
                        },
                        new
                        {
                            Id = 20,
                            Name = "Emily Watson"
                        },
                        new
                        {
                            Id = 21,
                            Name = "Paul Ritter"
                        },
                        new
                        {
                            Id = 22,
                            Name = "Úrsula Corberó"
                        },
                        new
                        {
                            Id = 23,
                            Name = "Álvaro Morte"
                        },
                        new
                        {
                            Id = 24,
                            Name = "Itziar Ituño"
                        },
                        new
                        {
                            Id = 25,
                            Name = "Miguel Herrán"
                        },
                        new
                        {
                            Id = 26,
                            Name = "Sofía Vergara"
                        },
                        new
                        {
                            Id = 27,
                            Name = "Eric Stonestreet"
                        },
                        new
                        {
                            Id = 28,
                            Name = "Julie Bowen"
                        },
                        new
                        {
                            Id = 29,
                            Name = "Sarah Hyland"
                        },
                        new
                        {
                            Id = 30,
                            Name = "Pedro Pascal"
                        },
                        new
                        {
                            Id = 31,
                            Name = "Gina Carano"
                        },
                        new
                        {
                            Id = 32,
                            Name = "Giancarlo Esposito"
                        },
                        new
                        {
                            Id = 33,
                            Name = "Carl Weathers"
                        },
                        new
                        {
                            Id = 34,
                            Name = "Daniel Radcliffe"
                        },
                        new
                        {
                            Id = 35,
                            Name = "Emma Watson"
                        },
                        new
                        {
                            Id = 36,
                            Name = "Rupert Grint"
                        },
                        new
                        {
                            Id = 37,
                            Name = "Chloe Bennet"
                        },
                        new
                        {
                            Id = 38,
                            Name = "Elizabeth Henstridge"
                        },
                        new
                        {
                            Id = 39,
                            Name = "Ming‑Na Wen"
                        },
                        new
                        {
                            Id = 40,
                            Name = "Emma Thompson"
                        },
                        new
                        {
                            Id = 41,
                            Name = "Russell Tovey"
                        },
                        new
                        {
                            Id = 42,
                            Name = "Ruth Madeley"
                        },
                        new
                        {
                            Id = 43,
                            Name = "Lucas Till"
                        },
                        new
                        {
                            Id = 44,
                            Name = "Tristin Mays"
                        },
                        new
                        {
                            Id = 45,
                            Name = "Meredith Eaton"
                        },
                        new
                        {
                            Id = 46,
                            Name = "Ellen Pompeo"
                        },
                        new
                        {
                            Id = 47,
                            Name = "Chandra Wilson"
                        },
                        new
                        {
                            Id = 48,
                            Name = "James Pickens Jr."
                        },
                        new
                        {
                            Id = 49,
                            Name = "Zendaya"
                        },
                        new
                        {
                            Id = 50,
                            Name = "Hunter Schafer"
                        },
                        new
                        {
                            Id = 51,
                            Name = "Jacob Elordi"
                        },
                        new
                        {
                            Id = 52,
                            Name = "Henry Cavil"
                        },
                        new
                        {
                            Id = 53,
                            Name = "Anya Chalotra"
                        },
                        new
                        {
                            Id = 54,
                            Name = "Freya Allan"
                        },
                        new
                        {
                            Id = 55,
                            Name = "Kiernan Shipka"
                        },
                        new
                        {
                            Id = 56,
                            Name = "Ross Lynch"
                        },
                        new
                        {
                            Id = 57,
                            Name = "Gavin Leatherwood"
                        },
                        new
                        {
                            Id = 58,
                            Name = "Zoe Saldana"
                        },
                        new
                        {
                            Id = 59,
                            Name = "Sam Worthington"
                        },
                        new
                        {
                            Id = 60,
                            Name = "Sigourney Weaver"
                        });
                });

            modelBuilder.Entity("MovieBuff.Models.Media", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CoverImage")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MediaType")
                        .HasColumnType("int");

                    b.Property<double>("Rating")
                        .HasColumnType("float");

                    b.Property<DateTime>("ReleaseDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Medias");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CoverImage = "https://kbimages1-a.akamaihd.net/538b1473-6d45-47f4-b16e-32a0a6ba7f9a/1200/1200/False/star-wars-episode-iv-a-new-hope-3.jpg",
                            Description = "After Princess Leia, the leader of the Rebel Alliance, is held hostage by Darth Vader, Luke and Han Solo must free her and destroy the powerful weapon created by the Galactic Empire.",
                            MediaType = 1,
                            Rating = 5.0,
                            ReleaseDate = new DateTime(1997, 5, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Star Wars: A New Hope (Episode IV)"
                        },
                        new
                        {
                            Id = 2,
                            CoverImage = "https://images.penguinrandomhouse.com/cover/9780345320223",
                            Description = "Darth Vader is adamant about turning Luke Skywalker to the dark side. Master Yoda trains Luke to become a Jedi Knight while his friends try to fend off the Imperial fleet.",
                            MediaType = 1,
                            Rating = 4.7999999999999998,
                            ReleaseDate = new DateTime(1980, 5, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Star Wars: The Empire Strikes Back (Episode V)"
                        },
                        new
                        {
                            Id = 3,
                            CoverImage = "https://static.wikia.nocookie.net/riverdalearchie/images/3/3a/Season_2_Poster.jpg",
                            Description = "Archie, Betty, Jughead and Veronica tackle being teenagers in a town that is rife with sinister happenings and blood-thirsty criminals.",
                            MediaType = 2,
                            Rating = 4.5,
                            ReleaseDate = new DateTime(2017, 1, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Riverdale"
                        },
                        new
                        {
                            Id = 4,
                            CoverImage = "https://static.wikia.nocookie.net/blacklist/images/5/57/Season_7_Poster.jpg",
                            Description = "A wanted fugitive mysteriously surrenders himself to the FBI and offers to help them capture deadly criminals. His sole condition is that he will work only with the new profiler, Elizabeth Keen.",
                            MediaType = 2,
                            Rating = 5.0,
                            ReleaseDate = new DateTime(2013, 9, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "The Blacklist"
                        },
                        new
                        {
                            Id = 5,
                            CoverImage = "https://m.media-amazon.com/images/I/91LlN7J+Z9L._SL1500_.jpg",
                            Description = "Luke Skywalker attempts to bring his father back to the light side of the Force. At the same time, the rebels hatch a plan to destroy the second Death Star.",
                            MediaType = 1,
                            Rating = 4.9000000000000004,
                            ReleaseDate = new DateTime(1983, 5, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Star Wars: Return of the Jedi (Episode VI)"
                        },
                        new
                        {
                            Id = 6,
                            CoverImage = "https://m.media-amazon.com/images/M/MV5BOTAzODEzNDAzMl5BMl5BanBnXkFtZTgwMDU1MTgzNzE@._V1_.jpg",
                            Description = "A new order threatens to destroy the New Republic. Finn, Rey and Poe, backed by the Resistance and the Republic, must find a way to stop them and find Luke, the last surviving Jedi.",
                            MediaType = 1,
                            Rating = 4.5,
                            ReleaseDate = new DateTime(2015, 11, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Star Wars: The Force Awakens (Episode VII)"
                        },
                        new
                        {
                            Id = 7,
                            CoverImage = "https://i.pinimg.com/originals/f4/5a/ea/f45aea75f65c0feb5cbe168f17a9a087.jpg",
                            Description = "Rey seeks to learn the ways of the Jedi under Luke Skywalker, its remaining member, to reinvigorate the Resistance's war against the First Order.",
                            MediaType = 1,
                            Rating = 4.9000000000000004,
                            ReleaseDate = new DateTime(2017, 11, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Star Wars: The Last Jedi (Episode VIII)"
                        },
                        new
                        {
                            Id = 8,
                            CoverImage = "https://lumiere-a.akamaihd.net/v1/images/star-wars-the-rise-of-skywalker-theatrical-poster-1000_ebc74357.jpeg?region=0%2C0%2C891%2C1372",
                            Description = "The revival of Emperor Palpatine resurrects the battle between the Resistance and the First Order while the Jedi's legendary conflict with the Sith Lord comes to a head.",
                            MediaType = 1,
                            Rating = 4.0,
                            ReleaseDate = new DateTime(2019, 11, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Star Wars: The Rise of Skywalker (Episode IX)"
                        },
                        new
                        {
                            Id = 9,
                            CoverImage = "https://play-lh.googleusercontent.com/sR1pzOxnF50WLR3vUqXYFvY01_tLD4XPn1RDHf0Xh-W04Vek_3iiZ98U7Db2JcmrqS8",
                            Description = "Jedi Knights Qui-Gon Jinn and Obi-Wan Kenobi set out to stop the Trade Federation from invading Naboo. While travelling, they come across a gifted boy, Anakin, and learn that the Sith have returned.",
                            MediaType = 1,
                            Rating = 3.5,
                            ReleaseDate = new DateTime(1999, 4, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Star Wars: The Phantom Menace (Episode I)"
                        },
                        new
                        {
                            Id = 10,
                            CoverImage = "https://m.media-amazon.com/images/M/MV5BMDAzM2M0Y2UtZjRmZi00MzVlLTg4MjEtOTE3NzU5ZDVlMTU5XkEyXkFqcGdeQXVyNDUyOTg3Njg@._V1_.jpg",
                            Description = "While pursuing an assassin, Obi Wan uncovers a sinister plot to destroy the Republic. With the fate of the galaxy hanging in the balance, the Jedi must defend the galaxy against the evil Sith.",
                            MediaType = 1,
                            Rating = 3.7999999999999998,
                            ReleaseDate = new DateTime(2002, 4, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Star Wars: Attack of the Clones (Episode II)"
                        },
                        new
                        {
                            Id = 11,
                            CoverImage = "https://play-lh.googleusercontent.com/mMyoXM8bf72KK-Udap4-hAvqqdXgn0AIBXkS8zejT0RXITIh8oK9a-SYIVk89CA0rHJi",
                            Description = "Anakin joins forces with Obi-Wan and sets Palpatine free from the evil clutches of Count Doku. However, he falls prey to Palpatine and the Jedis' mind games and gives into temptation.",
                            MediaType = 1,
                            Rating = 4.2000000000000002,
                            ReleaseDate = new DateTime(2005, 4, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Star Wars: Revenge of the Sith (Episode III)"
                        },
                        new
                        {
                            Id = 12,
                            CoverImage = "https://i.pinimg.com/originals/17/aa/71/17aa718c1ab15b482505b8431cf596fc.jpg",
                            Description = "Jake, who is paraplegic, replaces his twin on the Na'vi inhabited Pandora for a corporate mission. After the natives accept him as one of their own, he must decide where his loyalties lie.",
                            MediaType = 1,
                            Rating = 4.9000000000000004,
                            ReleaseDate = new DateTime(2009, 11, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Avatar"
                        },
                        new
                        {
                            Id = 13,
                            CoverImage = "https://i.pinimg.com/originals/06/b2/2f/06b22f1ec7b9a6914ec6255f40953e98.jpg",
                            Description = "In April 1986, the city of Chernobyl in the Soviet Union suffers one of the worst nuclear disasters in the history of mankind. Consequently, many heroes put their lives on the line to save Europe.",
                            MediaType = 2,
                            Rating = 3.6000000000000001,
                            ReleaseDate = new DateTime(2019, 4, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Chernobyl"
                        },
                        new
                        {
                            Id = 14,
                            CoverImage = "https://www.enigma-mag.com/wp-content/uploads/2019/08/1563490297.jpg",
                            Description = "A criminal mastermind who goes by \"The Professor\" has a plan to pull off the biggest heist in recorded history -- to print billions of euros in the Royal Mint of Spain. To help him carry out the ambitious plan, he recruits eight people with certain abilities and who have nothing to lose.",
                            MediaType = 2,
                            Rating = 4.0,
                            ReleaseDate = new DateTime(2017, 4, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "La Casa De Papel"
                        },
                        new
                        {
                            Id = 15,
                            CoverImage = "https://upload.wikimedia.org/wikipedia/en/thumb/0/09/Modern_Family_Season_Two_DVD_Cover.png/250px-Modern_Family_Season_Two_DVD_Cover.png",
                            Description = "Three modern-day families from California try to deal with their kids, quirky spouses and jobs in their own unique ways, often falling into hilarious situations.",
                            MediaType = 2,
                            Rating = 4.2999999999999998,
                            ReleaseDate = new DateTime(2009, 8, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Modern Family"
                        },
                        new
                        {
                            Id = 16,
                            CoverImage = "https://lumiere-a.akamaihd.net/v1/images/p_fyc_themandalorian_19097_de619ea9.jpeg",
                            Description = "After the defeat of the Empire at the hands of Rebel forces, a lone bounty hunter operating in the Outer Rim, away from the dominion of the New Republic, goes on many surprising and risky adventures.",
                            MediaType = 2,
                            Rating = 4.2000000000000002,
                            ReleaseDate = new DateTime(2019, 10, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "The Mandalorian"
                        },
                        new
                        {
                            Id = 17,
                            CoverImage = "https://movieguise.files.wordpress.com/2016/01/potter.jpg",
                            Description = "Harry Potter, an eleven-year-old orphan, discovers that he is a wizard and is invited to study at Hogwarts. Even as he escapes a dreary life and enters a world of magic, he finds trouble awaiting him.",
                            MediaType = 1,
                            Rating = 4.5999999999999996,
                            ReleaseDate = new DateTime(2001, 11, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Harry Potter and the Philosopher's Stone"
                        },
                        new
                        {
                            Id = 18,
                            CoverImage = "https://www.hylandcinema.com/files/hyland/movie-posters/hp-_chamber.jpg",
                            Description = "A house-elf warns Harry against returning to Hogwarts, but he decides to ignore it. When students and creatures at the school begin to get petrified, Harry finds himself surrounded in mystery.",
                            MediaType = 1,
                            Rating = 4.4000000000000004,
                            ReleaseDate = new DateTime(2002, 11, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Harry Potter and The Chamber Of Secrets"
                        },
                        new
                        {
                            Id = 19,
                            CoverImage = "https://static.wikia.nocookie.net/warner-bros-entertainment/images/c/cb/Harry-potter-and-the-prisoner-of-azkaban-movie-poster-style-f-11x17.jpg",
                            Description = "Harry, Ron and Hermoine return to Hogwarts just as they learn about Sirius Black and his plans to kill Harry. However, when Harry runs into him, he learns that the truth is far from reality.",
                            MediaType = 1,
                            Rating = 4.0,
                            ReleaseDate = new DateTime(2004, 5, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Harry Potter and The Prisoner Of Azkaban"
                        },
                        new
                        {
                            Id = 20,
                            CoverImage = "https://static.wikia.nocookie.net/marvelcinematicuniverse/images/1/10/AoS_Season_One_Poster.jpg",
                            Description = "Agent Phil Coulson leads a team of highly skilled agents from the global law-enforcement organisation known as S.H.I.E.L.D. Together, they combat extraordinary and inexplicable threats.",
                            MediaType = 2,
                            Rating = 4.9000000000000004,
                            ReleaseDate = new DateTime(2013, 9, 24, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Agents of S.H.I.E.L.D."
                        },
                        new
                        {
                            Id = 21,
                            CoverImage = "https://i.pinimg.com/474x/4e/96/06/4e9606a7f386cafa7903e28e94e43627.jpg",
                            Description = "An ordinary British family contends with the hopes, anxieties and joys of an uncertain future in this six-part limited series that begins in 2019 and propels the characters 15 years forward into an unstable world.",
                            MediaType = 2,
                            Rating = 2.7000000000000002,
                            ReleaseDate = new DateTime(2019, 5, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Years and Years"
                        },
                        new
                        {
                            Id = 22,
                            CoverImage = "https://m.media-amazon.com/images/M/MV5BMTg1NzUzNmQtMWI2ZC00YzdlLWI5ZTgtMGM3MjJlZTgwYTVlXkEyXkFqcGdeQXVyMTIzMzY2NDQ2._V1_FMjpg_UX1000_.jpg",
                            Description = "MacGyver, a contemporary hero and role model, applies his scientific knowledge to ordinary items to create a means of escape for himself and others from impending doom.",
                            MediaType = 2,
                            Rating = 3.2999999999999998,
                            ReleaseDate = new DateTime(2016, 9, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "MacGyver"
                        },
                        new
                        {
                            Id = 23,
                            CoverImage = "http://www.gstatic.com/tv/thumb/tvbanners/17114349/p17114349_b_v12_aa.jpg",
                            Description = "Surgical interns and their supervisors embark on a medical journey where they become part of heart-wrenching stories and make life-changing decisions in order to become the finest doctors.",
                            MediaType = 2,
                            Rating = 5.0,
                            ReleaseDate = new DateTime(2005, 3, 27, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Grey's Anatomy"
                        },
                        new
                        {
                            Id = 24,
                            CoverImage = "https://lanetechchampion.org/wp-content/uploads/2020/09/zendya-euphoria.jpg",
                            Description = "An American adaptation of the Israeli show of the same name, \"Euphoria\" follows the troubled life of 17-year-old Rue, a drug addict fresh from rehab with no plans to stay clean.",
                            MediaType = 2,
                            Rating = 3.0,
                            ReleaseDate = new DateTime(2019, 6, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Euphoria"
                        },
                        new
                        {
                            Id = 25,
                            CoverImage = "https://www.syfy.com/sites/syfy/files/styles/1170xauto/public/the-witcher-season-2-poster-vertical.jpg",
                            Description = "The witcher Geralt, a mutated monster hunter, struggles to find his place in a world in which people often prove more wicked than beasts.",
                            MediaType = 2,
                            Rating = 5.0,
                            ReleaseDate = new DateTime(2019, 12, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "The Witcher"
                        },
                        new
                        {
                            Id = 26,
                            CoverImage = "https://images-na.ssl-images-amazon.com/images/I/81bLWVTR3sL.jpg",
                            Description = "This adaptation of the \"Sabrina the Teenage Witch\" tale is a dark coming-of-age story that traffics in horror and the occult. In the reimagined origin story, Sabrina Spellman wrestles to reconcile her dual nature - half-witch, half-mortal.",
                            MediaType = 2,
                            Rating = 4.0999999999999996,
                            ReleaseDate = new DateTime(2018, 10, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Chilling Adventures of Sabrina"
                        });
                });

            modelBuilder.Entity("MovieBuff.Models.Rating", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("RatedMediaId")
                        .HasColumnType("int");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.Property<double>("Value")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("RatedMediaId");

                    b.HasIndex("UserId");

                    b.ToTable("Ratings");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            RatedMediaId = 1,
                            Value = 5.0
                        },
                        new
                        {
                            Id = 2,
                            RatedMediaId = 2,
                            Value = 4.7999999999999998
                        },
                        new
                        {
                            Id = 3,
                            RatedMediaId = 3,
                            Value = 4.5
                        },
                        new
                        {
                            Id = 4,
                            RatedMediaId = 4,
                            Value = 5.0
                        },
                        new
                        {
                            Id = 5,
                            RatedMediaId = 5,
                            Value = 4.9000000000000004
                        },
                        new
                        {
                            Id = 6,
                            RatedMediaId = 6,
                            Value = 4.5
                        },
                        new
                        {
                            Id = 7,
                            RatedMediaId = 7,
                            Value = 4.9000000000000004
                        },
                        new
                        {
                            Id = 8,
                            RatedMediaId = 8,
                            Value = 4.0
                        },
                        new
                        {
                            Id = 9,
                            RatedMediaId = 9,
                            Value = 3.5
                        },
                        new
                        {
                            Id = 10,
                            RatedMediaId = 10,
                            Value = 3.7999999999999998
                        },
                        new
                        {
                            Id = 11,
                            RatedMediaId = 11,
                            Value = 4.2000000000000002
                        },
                        new
                        {
                            Id = 12,
                            RatedMediaId = 12,
                            Value = 4.9000000000000004
                        },
                        new
                        {
                            Id = 13,
                            RatedMediaId = 13,
                            Value = 3.6000000000000001
                        },
                        new
                        {
                            Id = 14,
                            RatedMediaId = 14,
                            Value = 4.0
                        },
                        new
                        {
                            Id = 15,
                            RatedMediaId = 15,
                            Value = 4.2999999999999998
                        },
                        new
                        {
                            Id = 16,
                            RatedMediaId = 16,
                            Value = 4.2000000000000002
                        },
                        new
                        {
                            Id = 17,
                            RatedMediaId = 17,
                            Value = 4.5999999999999996
                        },
                        new
                        {
                            Id = 18,
                            RatedMediaId = 18,
                            Value = 4.4000000000000004
                        },
                        new
                        {
                            Id = 19,
                            RatedMediaId = 19,
                            Value = 4.0
                        },
                        new
                        {
                            Id = 20,
                            RatedMediaId = 20,
                            Value = 4.9000000000000004
                        },
                        new
                        {
                            Id = 21,
                            RatedMediaId = 21,
                            Value = 2.7000000000000002
                        },
                        new
                        {
                            Id = 22,
                            RatedMediaId = 22,
                            Value = 3.2999999999999998
                        },
                        new
                        {
                            Id = 23,
                            RatedMediaId = 23,
                            Value = 5.0
                        },
                        new
                        {
                            Id = 24,
                            RatedMediaId = 24,
                            Value = 3.0
                        },
                        new
                        {
                            Id = 25,
                            RatedMediaId = 25,
                            Value = 5.0
                        },
                        new
                        {
                            Id = 26,
                            RatedMediaId = 26,
                            Value = 4.0999999999999996
                        });
                });

            modelBuilder.Entity("MovieBuff.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte[]>("PasswordHash")
                        .HasColumnType("varbinary(max)");

                    b.Property<byte[]>("PasswordSalt")
                        .HasColumnType("varbinary(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("CastMemberMedia", b =>
                {
                    b.HasOne("MovieBuff.Models.CastMember", null)
                        .WithMany()
                        .HasForeignKey("CastId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MovieBuff.Models.Media", null)
                        .WithMany()
                        .HasForeignKey("StarredMediaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MovieBuff.Models.Rating", b =>
                {
                    b.HasOne("MovieBuff.Models.Media", "RatedMedia")
                        .WithMany("RatingList")
                        .HasForeignKey("RatedMediaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MovieBuff.Models.User", "User")
                        .WithMany("MyRatings")
                        .HasForeignKey("UserId");

                    b.Navigation("RatedMedia");

                    b.Navigation("User");
                });

            modelBuilder.Entity("MovieBuff.Models.Media", b =>
                {
                    b.Navigation("RatingList");
                });

            modelBuilder.Entity("MovieBuff.Models.User", b =>
                {
                    b.Navigation("MyRatings");
                });
#pragma warning restore 612, 618
        }
    }
}
